---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

#- name: "Upgrade packages"
#  become: yes
#  apt:
#    upgrade: yes

- name: "Install node dependencies"
  become: true
  apt:
    name:
      - nodejs
      - npm
    state: present 
    update_cache: true
- name: "Install pm2"
  become: true
  npm:
    name: pm2 
    global: true
    production: true 
    state: present 
