---
- name: copy backend folder archive to EC2
  become: yes
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract tar archive on the ubuntu server
  become: yes
  shell: |
    cd /home/ubuntu
    tar xzf artifact.tar.gz .

- name: "Install node dependencies"
  become: yes
  apt:
    name:
      - nodejs
      - npm
    state: present 
    update_cache: true

- name: "Start pm2"
  become: yes
  become_user: ubuntu
  shell: | 
    export PM2_HOME=/home/ubuntu
    npm install
    pm2 stop default
    cd /home/ubuntu
    pm2 start npm --name backend -- start

  environment: 
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    