---
- name: copy backend folder archive to EC2
  become: yes
  copy:
    src: /home/circlci/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract tar archive on the ubuntu server
  become: yes
  shell: |
    cd /home/ubuntu
    tar xzf artifact.tar.gz .

- name: "Install node dependencies"
  become: yes
  apt:
    name:
      - nodejs
      - npm
    state: present 
    update_cache: true

- name: "Start pm2"
  become: yes
  shell: | 
    pm2 stop default
    cd /home/ubuntu
    pm2 start npm --name backend -- start
    